### ISSUE TITLE
it's slower than 1 thread

### ISSUE THREAD

**Issue by lordspace** [porjo/braid#2]
I tested this library and it doesn't produce the speed the  I hoped for.

you can try downloading
http://ipv4.download.thinkbroadband.com/100MB.zip

**Comment by porjo** [comment]
Braid is useful in scenarios where a single TCP stream is limited for some reason (e.g. WAN link with high latency and some packet loss). Setting up multiple streams can provide an aggregate bandwidth that is greater than a single stream is capable of.

**Comment by lordspace** [comment]
cool
